CREATE TABLE `checkdisk` (
	`PC` VARCHAR(50) NULL DEFAULT NULL,
	`disk` VARCHAR(50) NULL DEFAULT NULL,
	`02` VARCHAR(50) NULL DEFAULT NULL,
	`05` VARCHAR(50) NULL DEFAULT NULL,
	`C4` VARCHAR(50) NULL DEFAULT NULL,
	`C5` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
